Skip to content
Navigation Menu
CleanroomMC
/
GroovyScript

Type / to search
Code
Issues
9
Pull requests
9
Actions
Projects
Wiki
Security
Insights
Build Test Artifact
pass event as delegate and not as parameter when event class is passe… #44
Jobs
Run details
Workflow file for this run
.github/workflows/test_build.yaml at dfcf525
# This workflow will build and upload test artifact
# Simple workflow with ignoring condition to prevent unneccessary build
# To download artifact check on job task

name: Build Test Artifact

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**' # Release GHA file, please change this when you change the file name
      - 'LICENSE' 
      - 'README.md'
      - 'examples/**'
      - 'editors/**'
      - '.editorconfig'
  workflow_dispatch:

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4.1.7
    
    # https://github.com/madhead/read-java-properties#error-java_home-is-set-to-an-invalid-directory
    - name: Gather Gradle properties
      uses: madhead/read-java-properties@latest
      id: gradle_properties
      with:
        file: gradle.properties
        all: true

    - name: Retrieve SHA short
      id: vars
      shell: bash
      run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Change mod version
      run: sed -i "s/mod_version.*=.*/mod_version = ${{ steps.gradle_properties.outputs.mod_version }}-${{ steps.vars.outputs.SHA_SHORT }}/g" gradle.properties

    - name: Set up Temurin JDK 8
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: gradle # Only cache stuff since test build action happen mostly

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.4.2

    - name: Build Project
      run: ./gradlew build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: GroovyScript-${{ steps.gradle_properties.outputs.modVersion }}-${{ github.run_number }}
        path: build/libs
pass event as delegate and not as parameter when event class is passed in listen method · CleanroomMC/GroovyScript@dfcf525


